[build]
	functions = "built-lambda/"
#	base = "ue-analytics/"
#	command = "npm run build"
#	publish = "build/"


# note: each of these fields are OPTIONAL, with an exception that when you're specifying "command" and "port", you must specify framework = "#custom"
[dev]
#	framework = "create-react-app" # or "#static" to force a static server
#	command = "npm start" # Command to start your dev server
#	targetPort = 3000 # The port for your application server, framework or site generator
#	port = 8888 # The port that the netlify dev will be accessible on
#	publish = "build" # The path to your static content folder
#	jwtRolePath = "app_metadata.authorization.roles" # Object path we should look for role values for JWT based redirects
#	autoLaunch = true # a Boolean value that determines if Netlify Dev launches the local server address in your browser